export const habitConstants = {
    ADD_HABIT_REQUEST: 'ADD_HABIT_REQUEST',
    ADD_HABIT_SUCCESS: 'ADD_HABIT_SUCCESS',
    ADD_HABIT_FAILURE: 'ADD_HABIT_FAILURE',

    HABIT_HISTORY_REQUEST: 'HABIT_HISTORY_REQUEST',
    HABIT_HISTORY_SUCCESS: 'HABIT_HISTORY_SUCCESS',
    HABIT_HISTORY_FAILURE: 'HABIT_HISTORY_FAILURE',

    HABIT_NOTES_REQUEST: 'HABIT_NOTES_REQUEST',
    HABIT_NOTES_SUCCESS: 'HABIT_NOTES_SUCCESS',
    HABIT_NOTES_FAILURE: 'HABIT_NOTES_FAILURE',

    REMOVE_NOTE_REQUEST: 'REMOVE_NOTE_REQUEST',
    REMOVE_NOTE_SUCCESS: 'REMOVE_NOTE_SUCCESS',
    REMOVE_NOTE_FAILURE: 'REMOVE_NOTE_FAILURE'
}