export const moodConstants = {
    ADD_MOOD: "ADD_MOOD",
    ADD_SUCCESS: "ADD_SUCCESS",
    ADD_ERROR: "ADD_ERROR",
    MOODHISTORY_REQUEST: 'MOODHISTORY_REQUEST',
    MOODHISTORY_SUCCESS: 'MOODHISTORY_SUCCESS',
    MOODHISTORY_FAILURE: 'MOODHISTORY_FAILURE',
    DATE_REQUEST: 'HISTORYDATE_REQUEST',
    DATE_SUCCESS: 'HISTORYDATE_SUCCESS',
    DATE_FAILURE: 'HISTORYDATE_FAILURE',
    NOTE_REQUEST: 'NOTE_REQUEST',
    NOTE_SUCCESS: 'NOTE_SUCCESS',
    NOTE_FAILURE: 'NOTE_FAILURE',

    REMOVE_MOODNOTE_REQUEST: 'REMOVE_MOODNOTE_REQUEST',
    REMOVE_MOODNOTE_SUCCESS: 'REMOVE_MOODNOTE_SUCCESS',
    REMOVE_MOODNOTE_FAILURE: 'REMOVE_MOODNOTE_FAILURE'
}