export const moodConstants = {
    ADD_MOOD: "ADD_MOOD",
    ADD_SUCCESS: "ADD_SUCCESS",
    ADD_ERROR: "ADD_ERROR",
    MOODHISTORY_REQUEST: 'MOODHISTORY_REQUEST',
    MOODHISTORY_SUCCESS: 'MOODHISTORY_SUCCESS',
    MOODHISTORY_FAILURE: 'MOODHISTORY_FAILURE'
}