export const skillConstants = {
    ADD_SKILL_REQUEST: 'ADD_SKILL_REQUEST',
    ADD_SKILL_SUCCESS: 'ADD_SKILL_SUCCESS',
    ADD_SKILL_FAILURE: 'ADD_SKILL_FAILURE',

    EDIT_SKILL_REQUEST: 'EDIT_SKILL_REQUEST',
    EDIT_SKILL_SUCCESS: 'EDIT_SKILL_SUCCESS',
    EDIT_SKILL_FAILURE: 'EDIT_SKILL_FAILURE',

    SHOW_SKILL_REQUEST: 'SHOW_SKILL_REQUEST',
    SHOW_SKILL_SUCCESS: 'SHOW_SKILL_SUCCESS',
    SHOW_SKILL_FAILURE: 'SHOW_SKILL_FAILURE',

    FETCH_SKILLS_REQUEST: 'FETCH_SKILLS_REQUEST',
    FETCH_SKILLS_SUCCESS: 'FETCH_SKILLS_SUCCESS',
    FETCH_SKILLS_FAILURE: 'FETCH_SKILLS_FAILURE'
}